#!/bin/bash

# @file ttt_board_s
#
# Defines board and functions for tic-tac-toe (naughts and crosses)
# This implementation uses a string to represent the board
#
# @date Jan 1, 2020
# @author philip gust
#

##
#  Initialize empty board.
#
#  @return 0 and outputs the empty board to stdout
#
initBoard() {
    declare iniboard=$1
    iniboard="_________"
    printf $iniboard
    return 0
}

##
#  Mark the board position with the marker of a player (X or O).
#  
#  @param marker the marker for a player (X or O)
#  @param boardPos the row major position on the board (1-9)
#  @param board the board
#  @return 0 and outputs new board to stdout if board position 
#    marked, 1 and outputs original board to stdout if invalid 
#    marker or position
#
markBoard() {
    declare mark=$1
    declare -i place=$2
    declare iniboard=$3
    if [ "$place" -le 0 ] || [ "$place" -ge 10 ] || [ "${iniboard:$place-1:1}" == "X" ] || [ "${iniboard:$place-1:1}" == "O" ] ; then
        printf $iniboard
        return 1
    fi
    iniboard="${iniboard: 0: $place-1}$mark${iniboard:$place}"
    printf $iniboard
    return 0
    
}


hasWon() {
    declare -a countR=(0 0 0)
    declare -a countC=(0 0 0)
    declare -i diagonal=0
    declare -i oppoDiag=0
    declare mark=$1
    declare iniboard=$2
    
    for a in {0,1,2} ; do
        for b in {0,1,2}; do
            if [ "${iniboard:a*3+b:1}" == "$mark" ]; then
                (( countR[$a]++ ))
                (( countC[$b]++ ))
                if [ $(($a + $b)) == 2 ]; then ((oppoDiag++)); fi
                if [ "$a" == "$b" ]; then ((diagonal++)); fi
            fi
            if [ "${countR[$a]}" == "3" ] || [ "${countC[$b]}" == "3" ]; then return 0; fi
            if [ "$diagonal" == "3" ] || [ "$oppoDiag" == "3" ]; then return 0; fi
        done
    done
    return 1
}


displayBoard() {
    declare iniboard=$1
    echo "-------------"
    for a in {0,1,2}; do
        echo -n "|"
        for b in {0,1,2}; do
            echo -n " ${iniboard:$a*3+$b:1} |";
        done
        echo
    done
    echo "-------------"
}
